src/components/Button/Button.js, src/components/Button/index.js, tailwind.config.js
=> Add button component (#9)

src/app/layout.js, src/app/page.js
=> Add site container in layout component

src/app/globals.css, src/app/layout.js, src/app/page.js
Se añadieron las siguientes fuentes:
MuseoModerno: .font-museo
Kufman: .font-kufman
*Se mantiene Inter para todo el proyecto, si se necesitan las fuentes personalizadas se pone el nombre de clase
=> feat: Add fonts to CSS (#19)

src/app/page.js
(#56)
Cambiar texto del botón secundario de "Saber más" a "Agenda"
=> frontend: Cambiar "Saber más" por "Agenda" en botón secondary

src/components/Footer.jsx
Arreglado las rutas de las imágenes
=> fix: Solucionar rutas de las imagenes en el footer

src/app/agenda/page.js
Cambiado el texto "Día 9 de Febrero" y "Día 10 de Febrero" a "Viernes 9 de Febrero" y "Sábado 10 de Febrero"
=> fix: Cambiar texto de botones del timeline (#103)

src/app/donar/page.js, src/components/DonarSubtitulo.jsx
Creación del componente `DonarSubtitulo` y añadido a la página donar
=> feat: Agregar subtitulo de página donar (#69)

src/app/donar/page.js, src/components/DonarSubtitulo.jsx
Creado texto de contenido debajo del subtítulo de la página de donar
=> feat: Agregar texto de contenido de página de Donar (#70)

src/talks/talks.json
=> fix: fix typo at talks JSON file

src/talks/talks.json
=> fix: Modificar nombre de charlista: Daniela Riquelme Yáñez (#122)

src/talks/talks.json
=> fix: Corregir nombre charlista Yoshie (#126)

src/talks/talks.json
=> fix: Corregir nombre charlista Miguel Ángel Durán (#128)

src/talks/talks.json
=> fix: Corregir nombre charlista Agustin Soto por Agustín Soto (#131)

src/components/CountdownTimer.jsx
=> feat: se agrega componente a mostrar al terminar el contador

src/talks/talks.json
=> fix: Rocio mieres: Corregir tag (#142)

src/talks/talks.json
Añade las comunidades cocloses #146rrespondientes a los speakers
=> closes #146

src/app/layout.js, src/app/page.js, src/components/NavBar.jsx
#145
en layout cambié el padding para pantallas xl a 24 y agregué un padding para pantallas 2xl en 56
luego en page cambié los tamaños de pantallas lg y xl
#143
aumenté tamaño de icono de "h-3 w-3" a "h-5 w-5"
le di display absolute al menú, y al clickear cada link que "isNavbarOpen" cambié a false
=> fix: bug #145 y #143

src/components/CounterSubtitle.jsx
=> fix: Estilos texto home se desborda en resoluciones grandes

src/components/NavBar.jsx
=> fix: reaparece logo desaparecido

src/components/Title.jsx
#153  agregué Link al logo del title para que lleve a /
=> feat: #153 component title lleva a ruta /

src/components/Subtitle/Subtitle.js
=> fix: Cambiar +30 charlistas por +40 charlistas (#159)

src/app/donar/page.js
=> fix: Contenido de la página "Donar" largo en desktop (#167)

src/app/nosotros/page.js
Cambio en la redacción, eliminación de texto duplicado y corrección de errores ortográficos
=> fix: Corregir texto en "nosotros" (#170)

src/talks/talks.json
=> closes #188

src/components/DonateInfo.jsx
=> fix: #192 corregir espacio entre QR y texto

src/app/donar/page.js, src/app/nosotros/page.js
=> fix: #193, #200 padding en pantallas de 375px

src/components/NavBar.jsx
=> feat: change Donate button text placed in Navbar

src/app/page.js
Se cambia el texto "donar" por "ir a donar"
=> feat: UX Writing -> Botón del home (#214)

src/components/DonateInfo.jsx
=> fix: soluciona problema de layout en página de donar

src/app/page.js, src/components/Button/Button.js, src/components/DonateInfo.jsx, src/components/NavBar.jsx
=> fix: Mobile - Boton twitch padding (#213)

src/components/NumberBox.jsx
=> fix: se soluciona problema de animación de bordes del timer

src/app/agenda/client-page.js, src/components/Timeline.jsx
=> Some timeline improvements

src/components/DonateInfo.jsx
- Utilize CSS grid for center alignment and consistent spacing.
- Implement clamp function for dynamic text resizing across devices.
- Remove explicit line break in favor of gap utility for better spacing control.
- Add `md:min-w-96` to set a minimum width for medium screen sizes.
- Use `lg:min-w-fit` to adjust minimum width for larger screens, ensuring content adapts more gracefully.
This update enhances the mobile and desktop visual presentation of the total donation amount, ensuring a better user experience across all devices.
=> Fix: improve responsiveness of donation total display 

src/app/agenda/client-page.js, src/components/NavBar.jsx
This change enhances readability and maintainability of the component's styling logic, especially for the mobile version's visibility and animation effects.
- Implement `cn` utility for dynamic class names based on `isNavbarOpen` state.
- Improve responsive design with better structured and semantic class naming.
- Enhance accessibility and user experience on mobile devices.
- Decrease the z-index of the top container from 20 to 10 for better layering control.
- Add `flex-wrap` to the child flex container to enhance content responsiveness and layout adaptability.
This update enhances the mobile and desktop visual presentation of the total donation amount, ensuring a better user experience across all devices.
https://github.com/JSConfCL/TechTon-landing/assets/14036522/2bb6b9d4-ea62-4add-b3f …
=> Refactor: enhance mobile navigation visibility and structure 

src/communities/communities.json, src/components/CommunityLogos/index.js
Se agregan links a los logos de las comunidades y animación al hacerle hover
=> Sea gregan links a logos de comunidades

src/app/page.js, src/components/CounterSubtitle.jsx, src/components/DonarSubtitulo.jsx, src/components/DonateInfo.jsx, src/components/NavBar.jsx
Closes #257 
Se remueven  la sección para donar y compartir así como los textos que invitan a los usuarios a donar
=> remove donate section and modify texts
